import _HomeContainer from "./home";
import _LoginContainer from "./login";
import _PageNotFound from "./404";
import _OrderManagementTable from "./ordermanagementtable";
import _PunchedOrders from "./punchedorders";
import _RestaurantManagementTable from "./restaurantmanagementtable";
import _AddRestaurant from "./addrestaurant";
import _AddOrderStatus from "./addorderstatus";
import _AddCategory from "./addcategory";
import _AddItem from "./additem";
import _AddCuisine from "./addcuisine";
import _AddAddons from "./addaddons";
import _OrderDetails from "./orderdetails";
import _CustomerManagementTable from "./customermanagementtable";
import _AddAddonCategory from "./addaddoncategory";
import _AddAddonItem from "./addaddonitem";
import _ChangePassword from "./changepassword";
import _Faqs from "./faqs";
import _Termsandconditions from "./termsandconditions";

export const OrderDetails = _OrderDetails;
export const HomeContainer = _HomeContainer;
export const LoginContainer = _LoginContainer;
export const PageNotFound = _PageNotFound;
export const OrderManagementTable = _OrderManagementTable;
export const PunchedOrders = _PunchedOrders;
export const RestaurantManagementTable = _RestaurantManagementTable;
export const AddRestaurant = _AddRestaurant;
export const AddOrderStatus = _AddOrderStatus;
export const AddCategory = _AddCategory;
export const AddItem = _AddItem;
export const AddCuisine = _AddCuisine;
export const AddAddons = _AddAddons;
export const CustomerManagementTable = _CustomerManagementTable;
export const AddAddonCategory = _AddAddonCategory;
export const AddAddonItem = _AddAddonItem;
export const ChangePassword = _ChangePassword;
export const Faqs = _Faqs;
export const Termsandconditions = _Termsandconditions;
