import _Header from "./header";
import _Footer from "./footer";
import _Layout from "./layout";
import _LeftMenu from "./leftmenu";
import _TopMenu from "./topmenu";
import _BChart from "./barchart";
import _LChart from "./linechart";
import _DataCounter from "./datacounter";
import _Chart from "./chart";
import _OrderTable from "./ordertable";
import _NewOrder from "./neworder";
import _PunchedOrderDesc from "./punchedorderdesc";
import _NewRestaurant from "./newrestaurant";
import _RestaurantTable from "./restauranttable";
import _Navbar from "./navbar";
import _AddRestaurantForm from "./addrestaurantform";

export const Header = _Header;
export const Footer = _Footer;
export const Layout = _Layout;
export const LeftMenu = _LeftMenu;
export const TopMenu = _TopMenu;
export const BChart = _BChart;
export const LChart = _LChart;
export const DataCounter = _DataCounter;
export const Chart = _Chart;
export const OrderTable = _OrderTable;
export const NewOrder = _NewOrder;
export const PunchedOrderDesc = _PunchedOrderDesc;
export const NewRestaurant = _NewRestaurant;
export const RestaurantTable = _RestaurantTable;
export const Navbar = _Navbar;
export const AddRestaurantForm = _AddRestaurantForm;
