import _Header from "./header";
import _Footer from "./footer";
import _Layout from "./layout";
import _TopMenu from "./topmenu";
import _BChart from "./barchart";
import _LChart from "./linechart";
import _DataCounter from "./datacounter";
import _Chart from "./chart";
import _OrderTable from "./ordertable";
import _NewOrder from "./neworder";
import _PunchedOrderDesc from "./punchedorderdesc";
import _NewRestaurant from "./newrestaurant";
import _RestaurantTable from "./restauranttable";
import _Navbar from "./navbar";
import _AddRestaurantForm from "./addrestaurantform";
import _ImageUpload from "./imageuploader";
import _AddOrderStatusForm from "./addorderstatusform";
import _AddCategoryForm from "./addcategoryform";
import _AddItemFrom from "./additemform";
import _AddCuisineForm from "./addcuisineform";
import _AddAddonForm from "./newaddon";
import _OrderDetailsForn from "./orderdetailscreen";
import _CustomerTable from "./customertable";
import _NewCustomer from "./newcustomer";
import _AddAddonCategoryForm from "./addaddoncategoryform";
import _AddAddonItemForm from "./addaddonitemform";
import _Faqdetails from "./faqdetails";
import _Termsandconditionsform from "./termsandconditionsform";
import _SitemapForm from "./sitemapform";
import _ReviewTableShort from "./reviewtableshort";
import _ReviewTableDetail from "./reviewtabledetail";
import _ReviewTableDetailRating from "./reviewtabledetailrating";

export const OrderDetailsForn = _OrderDetailsForn;
export const Header = _Header;
export const Footer = _Footer;
export const Layout = _Layout;
export const TopMenu = _TopMenu;
export const BChart = _BChart;
export const LChart = _LChart;
export const DataCounter = _DataCounter;
export const Chart = _Chart;
export const OrderTable = _OrderTable;
export const NewOrder = _NewOrder;
export const PunchedOrderDesc = _PunchedOrderDesc;
export const NewRestaurant = _NewRestaurant;
export const RestaurantTable = _RestaurantTable;
export const Navbar = _Navbar;
export const AddRestaurantForm = _AddRestaurantForm;
export const ImageUpload = _ImageUpload;
export const AddOrderStatusForm = _AddOrderStatusForm;
export const AddCategoryForm = _AddCategoryForm;
export const AddItemFrom = _AddItemFrom;
export const AddCuisineForm = _AddCuisineForm;
export const AddAddonForm = _AddAddonForm;
export const CustomerTable = _CustomerTable;
export const NewCustomer = _NewCustomer;
export const AddAddonCategoryForm = _AddAddonCategoryForm;
export const AddAddonItemForm = _AddAddonItemForm;
export const Faqdetails = _Faqdetails;
export const Termsandconditionsform = _Termsandconditionsform;
export const SitemapForm = _SitemapForm;
export const ReviewTableShort = _ReviewTableShort;
export const ReviewTableDetail = _ReviewTableDetail;
export const ReviewTableDetailRating = _ReviewTableDetailRating;
